# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft
minecraft_version=26.2.0
minecraft_version_range=[26.2.0,)
# https://projects.neoforged.net/neoforged/neogradle
neogradle_version=7.1.38

# https://neoforged.net/
neoforge_version=26.2.0.7-beta
neoforge_version_range=[26.2.0.7-beta,)

# Mod Properties
mod_id=blahaj
mod_version=4.0.0+26.2
mod_name=Blåhaj - Replushed
mod_group_id=de.dafuqs
archives_base_name=blahaj-replushed
mod_license=Unlicense
mod_authors=hibi, DaFuqs, infoplayerstart, musicalskele
mod_description=Soft toy, shark mod, 16px.
issue_tracker_url=https://github.com/DaFuqs/Blahaj/issues
display_url=https://github.com/DaFuqs/Blahaj
